--Générer le DDL de tous les objets de HR

SELECT DBMS_METADATA.GET_DDL('TABLE', 'REGIONS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'COUNTRIES') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'LOCATIONS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'DEPARTMENTS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'JOBS') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'EMPLOYEES') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TABLE', 'JOB_HISTORY') FROM DUAL;

SELECT DBMS_METADATA.GET_DDL('VIEW', 'EMP_DETAILS_VIEW') FROM DUAL;
